USE forge_core;

-- Migracion para ampliar el catalogo de la demo con minimo 50 productos.
-- INSERT IGNORE evita duplicar categorias/marcas si la migracion se ejecuta mas de una vez.
INSERT IGNORE INTO categories (name, slug) VALUES
  ('GPU', 'gpu'),
  ('RAM', 'ram'),
  ('CPU', 'cpu'),
  ('SSD', 'ssd'),
  ('Fuente', 'fuente');

-- Marcas reales/ficticias usadas por el catalogo extendido.
INSERT IGNORE INTO brands (name) VALUES
  ('NVIDIA'),
  ('AMD'),
  ('Intel'),
  ('ASUS'),
  ('MSI'),
  ('Gigabyte'),
  ('ZOTAC'),
  ('Sapphire'),
  ('XFX'),
  ('PowerColor'),
  ('PNY'),
  ('ASRock'),
  ('Corsair'),
  ('G.Skill'),
  ('Kingston'),
  ('TeamGroup'),
  ('Crucial'),
  ('ADATA'),
  ('Patriot'),
  ('Samsung'),
  ('WD_BLACK'),
  ('Seagate'),
  ('Sabrent'),
  ('SK hynix'),
  ('Lexar'),
  ('Seasonic'),
  ('EVGA'),
  ('be quiet!'),
  ('Thermaltake'),
  ('Cooler Master');

-- Productos extendidos. Reutilizan las imagenes generadas para mantener la demo liviana.
INSERT INTO products (category_id, brand_id, slug, name, description, image_url, price, stock, rating, specs_json, active) VALUES
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'NVIDIA'), 'nvidia-geforce-rtx-4090-founders-edition', 'NVIDIA GeForce RTX 4090 Founders Edition', 'GPU extrema para gaming 4K, renderizado 3D e IA generativa.', '/assets/products/rtx-4090-ultra.jpg', 2199.00, 6, 4.9, JSON_ARRAY('24 GB GDDR6X', 'PCIe 4.0', 'DLSS 3', 'Ray Tracing'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'ASUS'), 'asus-rog-strix-rtx-4080-super', 'ASUS ROG Strix GeForce RTX 4080 SUPER', 'Tarjeta grafica premium para builds gamer de alto rendimiento.', '/assets/products/rtx-4090-ultra.jpg', 1499.00, 9, 4.8, JSON_ARRAY('16 GB GDDR6X', 'PCIe 4.0', 'Triple fan', 'Aura Sync'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'MSI'), 'msi-rtx-4070-ti-super-gaming-x-trio', 'MSI GeForce RTX 4070 Ti SUPER Gaming X Trio', 'GPU balanceada para gaming 1440p ultra y streaming.', '/assets/products/rtx-4090-ultra.jpg', 999.00, 12, 4.7, JSON_ARRAY('16 GB GDDR6X', 'DLSS 3', 'Tri Frozr', 'OC Edition'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'Gigabyte'), 'gigabyte-rtx-4070-windforce-oc', 'Gigabyte GeForce RTX 4070 Windforce OC', 'Grafica eficiente para equipos gamer compactos.', '/assets/products/rtx-4090-ultra.jpg', 679.00, 16, 4.6, JSON_ARRAY('12 GB GDDR6X', 'Windforce', 'PCIe 4.0', 'Ray Tracing'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'ZOTAC'), 'zotac-rtx-4060-twin-edge', 'ZOTAC Gaming GeForce RTX 4060 Twin Edge', 'GPU de entrada moderna para 1080p competitivo.', '/assets/products/rtx-4090-ultra.jpg', 349.00, 20, 4.4, JSON_ARRAY('8 GB GDDR6', 'Twin fan', 'DLSS 3', 'Compacta'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'AMD'), 'amd-radeon-rx-7900-xtx-reference', 'AMD Radeon RX 7900 XTX Reference', 'Tarjeta grafica Radeon para gaming 4K y creacion de contenido.', '/assets/products/rtx-4090-ultra.jpg', 1099.00, 10, 4.8, JSON_ARRAY('24 GB GDDR6', 'RDNA 3', 'DisplayPort 2.1', 'FSR'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'Sapphire'), 'sapphire-pulse-radeon-rx-7800-xt', 'Sapphire Pulse Radeon RX 7800 XT', 'GPU Radeon ideal para gaming 1440p con alto rendimiento por dolar.', '/assets/products/rtx-4090-ultra.jpg', 579.00, 14, 4.6, JSON_ARRAY('16 GB GDDR6', 'RDNA 3', 'Dual BIOS', 'FSR'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'XFX'), 'xfx-speedster-qick-319-rx-7700-xt', 'XFX Speedster QICK 319 Radeon RX 7700 XT', 'Grafica AMD con buena refrigeracion para sesiones largas.', '/assets/products/rtx-4090-ultra.jpg', 499.00, 15, 4.5, JSON_ARRAY('12 GB GDDR6', 'QICK 319', 'PCIe 4.0', 'RDNA 3'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'PowerColor'), 'powercolor-hellhound-rx-7600-xt', 'PowerColor Hellhound Radeon RX 7600 XT', 'GPU compacta para e-sports y juegos actuales en 1080p.', '/assets/products/rtx-4090-ultra.jpg', 369.00, 18, 4.4, JSON_ARRAY('16 GB GDDR6', 'Dual fan', 'RDNA 3', 'Silent mode'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'PNY'), 'pny-geforce-rtx-3060-verto-12gb', 'PNY GeForce RTX 3060 Verto 12GB', 'Grafica popular para trabajo creativo y gaming 1080p.', '/assets/products/rtx-4090-ultra.jpg', 299.00, 22, 4.3, JSON_ARRAY('12 GB GDDR6', 'PCIe 4.0', 'Ray Tracing', 'DLSS'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'Intel'), 'intel-arc-a770-limited-edition', 'Intel Arc A770 Limited Edition', 'GPU Intel para gaming moderno, AV1 y creacion multimedia.', '/assets/products/rtx-4090-ultra.jpg', 329.00, 8, 4.2, JSON_ARRAY('16 GB GDDR6', 'Xe HPG', 'AV1', 'Resizable BAR'), 1),
  ((SELECT id FROM categories WHERE slug = 'gpu'), (SELECT id FROM brands WHERE name = 'ASRock'), 'asrock-radeon-rx-7900-gre-steel-legend', 'ASRock Radeon RX 7900 GRE Steel Legend', 'GPU Radeon potente para 1440p y 4K con estilo blanco premium.', '/assets/products/rtx-4090-ultra.jpg', 699.00, 7, 4.7, JSON_ARRAY('16 GB GDDR6', 'RDNA 3', 'Steel Legend', 'Triple fan'), 1),

  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'AMD'), 'amd-ryzen-9-7950x3d', 'AMD Ryzen 9 7950X3D', 'Procesador de gama alta para gaming, streaming y creacion profesional.', '/assets/products/ryzen-9-forge.jpg', 699.00, 11, 4.9, JSON_ARRAY('16 nucleos', '32 hilos', '3D V-Cache', 'AM5'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'AMD'), 'amd-ryzen-9-7900x', 'AMD Ryzen 9 7900X', 'CPU potente para multitarea intensa y estaciones gamer.', '/assets/products/ryzen-9-forge.jpg', 429.00, 14, 4.7, JSON_ARRAY('12 nucleos', '24 hilos', '5.6 GHz boost', 'AM5'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'AMD'), 'amd-ryzen-7-7800x3d', 'AMD Ryzen 7 7800X3D', 'Procesador favorito para gaming por su cache 3D.', '/assets/products/ryzen-9-forge.jpg', 449.00, 18, 4.9, JSON_ARRAY('8 nucleos', '16 hilos', '3D V-Cache', 'AM5'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'AMD'), 'amd-ryzen-5-7600x', 'AMD Ryzen 5 7600X', 'CPU eficiente para equipos gamer modernos de gama media.', '/assets/products/ryzen-9-forge.jpg', 249.00, 24, 4.6, JSON_ARRAY('6 nucleos', '12 hilos', '5.3 GHz boost', 'AM5'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'Intel'), 'intel-core-i9-14900k', 'Intel Core i9-14900K', 'Procesador enthusiast para gaming, render y workloads exigentes.', '/assets/products/ryzen-9-forge.jpg', 589.00, 10, 4.8, JSON_ARRAY('24 nucleos', '32 hilos', '6.0 GHz boost', 'LGA1700'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'Intel'), 'intel-core-i7-14700k', 'Intel Core i7-14700K', 'CPU de alto rendimiento para gaming y productividad.', '/assets/products/ryzen-9-forge.jpg', 429.00, 13, 4.7, JSON_ARRAY('20 nucleos', '28 hilos', '5.6 GHz boost', 'LGA1700'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'Intel'), 'intel-core-i5-14600k', 'Intel Core i5-14600K', 'Procesador balanceado para gaming competitivo y multitarea.', '/assets/products/ryzen-9-forge.jpg', 319.00, 18, 4.6, JSON_ARRAY('14 nucleos', '20 hilos', '5.3 GHz boost', 'LGA1700'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'Intel'), 'intel-core-i5-13400f', 'Intel Core i5-13400F', 'CPU de gran valor para builds gamer con GPU dedicada.', '/assets/products/ryzen-9-forge.jpg', 189.00, 25, 4.5, JSON_ARRAY('10 nucleos', '16 hilos', '4.6 GHz boost', 'Sin iGPU'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'AMD'), 'amd-ryzen-5-5600x', 'AMD Ryzen 5 5600X', 'Procesador AM4 clasico para actualizaciones economicas.', '/assets/products/ryzen-9-forge.jpg', 159.00, 28, 4.6, JSON_ARRAY('6 nucleos', '12 hilos', 'AM4', 'PCIe 4.0'), 1),
  ((SELECT id FROM categories WHERE slug = 'cpu'), (SELECT id FROM brands WHERE name = 'Intel'), 'intel-core-i3-13100f', 'Intel Core i3-13100F', 'CPU economica para PCs de entrada con buen rendimiento por nucleo.', '/assets/products/ryzen-9-forge.jpg', 119.00, 30, 4.3, JSON_ARRAY('4 nucleos', '8 hilos', 'LGA1700', 'Sin iGPU'), 1),

  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'Corsair'), 'corsair-vengeance-rgb-ddr5-32gb-6000', 'Corsair Vengeance RGB DDR5 32GB 6000MHz', 'Kit de memoria DDR5 RGB para equipos gamer modernos.', '/assets/products/venom-rgb-64gb.jpg', 139.00, 20, 4.7, JSON_ARRAY('32 GB', 'DDR5', '6000 MHz', 'RGB'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'G.Skill'), 'gskill-trident-z5-rgb-ddr5-32gb-6400', 'G.Skill Trident Z5 RGB DDR5 32GB 6400MHz', 'Memoria DDR5 de alta frecuencia para performance premium.', '/assets/products/venom-rgb-64gb.jpg', 169.00, 18, 4.8, JSON_ARRAY('32 GB', 'DDR5', '6400 MHz', 'CL32'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'Kingston'), 'kingston-fury-beast-ddr5-32gb-6000', 'Kingston Fury Beast DDR5 32GB 6000MHz', 'Kit DDR5 estable para gaming y productividad diaria.', '/assets/products/venom-rgb-64gb.jpg', 129.00, 22, 4.6, JSON_ARRAY('32 GB', 'DDR5', '6000 MHz', 'EXPO'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'TeamGroup'), 'teamgroup-tforce-delta-rgb-ddr5-32gb-6000', 'TeamGroup T-Force Delta RGB DDR5 32GB 6000MHz', 'Memoria RGB con gran presencia visual para builds gamer.', '/assets/products/venom-rgb-64gb.jpg', 124.00, 16, 4.5, JSON_ARRAY('32 GB', 'DDR5', '6000 MHz', 'RGB'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'Crucial'), 'crucial-pro-ddr5-32gb-5600', 'Crucial Pro DDR5 32GB 5600MHz', 'Memoria confiable para productividad, gaming ligero y upgrades.', '/assets/products/shadow-ram-32gb.jpg', 99.00, 26, 4.4, JSON_ARRAY('32 GB', 'DDR5', '5600 MHz', 'Low profile'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'Corsair'), 'corsair-dominator-titanium-ddr5-64gb-6600', 'Corsair Dominator Titanium DDR5 64GB 6600MHz', 'Kit DDR5 premium para estaciones de alto rendimiento.', '/assets/products/venom-rgb-64gb.jpg', 329.00, 9, 4.9, JSON_ARRAY('64 GB', 'DDR5', '6600 MHz', 'RGB'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'G.Skill'), 'gskill-ripjaws-s5-ddr5-32gb-6000', 'G.Skill Ripjaws S5 DDR5 32GB 6000MHz', 'Memoria sobria de baja latencia para builds discretos.', '/assets/products/shadow-ram-32gb.jpg', 119.00, 21, 4.6, JSON_ARRAY('32 GB', 'DDR5', '6000 MHz', 'CL30'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'ADATA'), 'adata-xpg-lancer-rgb-ddr5-32gb-6000', 'ADATA XPG Lancer RGB DDR5 32GB 6000MHz', 'Kit RGB DDR5 para equipos gamer con buena compatibilidad.', '/assets/products/venom-rgb-64gb.jpg', 125.00, 18, 4.5, JSON_ARRAY('32 GB', 'DDR5', '6000 MHz', 'RGB'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'Patriot'), 'patriot-viper-venom-ddr5-32gb-6200', 'Patriot Viper Venom DDR5 32GB 6200MHz', 'Memoria rapida para gaming, streaming y multitarea.', '/assets/products/shadow-ram-32gb.jpg', 139.00, 17, 4.5, JSON_ARRAY('32 GB', 'DDR5', '6200 MHz', 'XMP'), 1),
  ((SELECT id FROM categories WHERE slug = 'ram'), (SELECT id FROM brands WHERE name = 'Kingston'), 'kingston-fury-renegade-rgb-ddr5-64gb-6400', 'Kingston Fury Renegade RGB DDR5 64GB 6400MHz', 'Kit DDR5 de alta capacidad para creadores y workstations.', '/assets/products/venom-rgb-64gb.jpg', 289.00, 8, 4.8, JSON_ARRAY('64 GB', 'DDR5', '6400 MHz', 'RGB'), 1),

  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Samsung'), 'samsung-990-pro-2tb-nvme', 'Samsung 990 PRO 2TB NVMe SSD', 'SSD NVMe de alto rendimiento para juegos y proyectos pesados.', '/assets/products/nova-ssd-4tb.jpg', 189.00, 20, 4.9, JSON_ARRAY('2 TB', 'PCIe 4.0', '7450 MB/s', 'NVMe'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'WD_BLACK'), 'wdblack-sn850x-2tb-nvme', 'WD_BLACK SN850X 2TB NVMe SSD', 'Almacenamiento gamer rapido para cargas y bibliotecas grandes.', '/assets/products/nova-ssd-4tb.jpg', 169.00, 18, 4.8, JSON_ARRAY('2 TB', 'PCIe 4.0', '7300 MB/s', 'NVMe'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Crucial'), 'crucial-t700-2tb-gen5-nvme', 'Crucial T700 2TB PCIe Gen5 NVMe SSD', 'SSD Gen5 ultra rapido para estaciones de nueva generacion.', '/assets/products/nova-ssd-4tb.jpg', 269.00, 11, 4.8, JSON_ARRAY('2 TB', 'PCIe 5.0', '12400 MB/s', 'Disipador'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Kingston'), 'kingston-kc3000-2tb-nvme', 'Kingston KC3000 2TB NVMe SSD', 'SSD NVMe rapido y confiable para gaming y creacion.', '/assets/products/nova-ssd-4tb.jpg', 159.00, 19, 4.7, JSON_ARRAY('2 TB', 'PCIe 4.0', '7000 MB/s', 'NVMe'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Seagate'), 'seagate-firecuda-530-2tb-nvme', 'Seagate FireCuda 530 2TB NVMe SSD', 'SSD premium con gran resistencia para juegos y trabajo pesado.', '/assets/products/nova-ssd-4tb.jpg', 199.00, 13, 4.7, JSON_ARRAY('2 TB', 'PCIe 4.0', '7300 MB/s', 'Alta resistencia'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Corsair'), 'corsair-mp600-pro-lpx-2tb-nvme', 'Corsair MP600 PRO LPX 2TB NVMe SSD', 'SSD NVMe con disipador, ideal para PC y consolas compatibles.', '/assets/products/nova-ssd-4tb.jpg', 179.00, 15, 4.6, JSON_ARRAY('2 TB', 'PCIe 4.0', '7100 MB/s', 'Disipador'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Sabrent'), 'sabrent-rocket-4-plus-2tb-nvme', 'Sabrent Rocket 4 Plus 2TB NVMe SSD', 'SSD Gen4 de alta velocidad para archivos y juegos grandes.', '/assets/products/nova-ssd-4tb.jpg', 179.00, 12, 4.6, JSON_ARRAY('2 TB', 'PCIe 4.0', '7100 MB/s', 'NVMe'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'SK hynix'), 'sk-hynix-platinum-p41-2tb-nvme', 'SK hynix Platinum P41 2TB NVMe SSD', 'SSD eficiente con gran rendimiento sostenido.', '/assets/products/nova-ssd-4tb.jpg', 149.00, 16, 4.7, JSON_ARRAY('2 TB', 'PCIe 4.0', '7000 MB/s', 'NVMe'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'Lexar'), 'lexar-nm790-4tb-nvme', 'Lexar NM790 4TB NVMe SSD', 'SSD NVMe de gran capacidad para bibliotecas de juegos y multimedia.', '/assets/products/nova-ssd-4tb.jpg', 259.00, 10, 4.6, JSON_ARRAY('4 TB', 'PCIe 4.0', '7400 MB/s', 'NVMe'), 1),
  ((SELECT id FROM categories WHERE slug = 'ssd'), (SELECT id FROM brands WHERE name = 'ADATA'), 'adata-legend-960-max-2tb-nvme', 'ADATA Legend 960 Max 2TB NVMe SSD', 'SSD NVMe con buen rendimiento para estaciones y gaming.', '/assets/products/nova-ssd-4tb.jpg', 149.00, 14, 4.5, JSON_ARRAY('2 TB', 'PCIe 4.0', '7400 MB/s', 'Disipador'), 1),

  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'Corsair'), 'corsair-rm1000x-shift-1000w', 'Corsair RM1000x Shift 1000W', 'Fuente modular ATX 3.0 para GPUs de alto consumo.', '/assets/products/titan-psu-1000w.jpg', 229.00, 12, 4.8, JSON_ARRAY('1000W', '80+ Gold', 'ATX 3.0', 'Modular'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'Seasonic'), 'seasonic-prime-tx-1000', 'Seasonic PRIME TX-1000', 'Fuente Titanium premium para builds silenciosos y estables.', '/assets/products/titan-psu-1000w.jpg', 329.00, 7, 4.9, JSON_ARRAY('1000W', '80+ Titanium', 'Modular', '12 anos garantia'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'EVGA'), 'evga-supernova-850-g6', 'EVGA SuperNOVA 850 G6', 'Fuente compacta y eficiente para equipos gamer potentes.', '/assets/products/titan-psu-1000w.jpg', 159.00, 14, 4.7, JSON_ARRAY('850W', '80+ Gold', 'Modular', 'Eco mode'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'be quiet!'), 'be-quiet-dark-power-13-1000w', 'be quiet! Dark Power 13 1000W', 'Fuente silenciosa ATX 3.0 para PCs premium.', '/assets/products/titan-psu-1000w.jpg', 289.00, 8, 4.8, JSON_ARRAY('1000W', '80+ Titanium', 'ATX 3.0', 'Silenciosa'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'Thermaltake'), 'thermaltake-toughpower-gf3-1000w', 'Thermaltake Toughpower GF3 1000W', 'Fuente lista para PCIe 5.0 y tarjetas graficas modernas.', '/assets/products/titan-psu-1000w.jpg', 199.00, 11, 4.6, JSON_ARRAY('1000W', '80+ Gold', 'PCIe 5.0', 'Modular'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'Cooler Master'), 'cooler-master-v850-sfx-gold', 'Cooler Master V850 SFX Gold', 'Fuente SFX compacta para builds mini ITX de alto rendimiento.', '/assets/products/titan-psu-1000w.jpg', 169.00, 9, 4.6, JSON_ARRAY('850W', '80+ Gold', 'SFX', 'Modular'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'MSI'), 'msi-mpg-a1000g-pcie5', 'MSI MPG A1000G PCIe5 1000W', 'Fuente modular preparada para GPUs con conector 12VHPWR.', '/assets/products/titan-psu-1000w.jpg', 189.00, 13, 4.7, JSON_ARRAY('1000W', '80+ Gold', 'PCIe 5.0', 'Modular'), 1),
  ((SELECT id FROM categories WHERE slug = 'fuente'), (SELECT id FROM brands WHERE name = 'ASUS'), 'asus-rog-thor-1200w-platinum-ii', 'ASUS ROG Thor 1200W Platinum II', 'Fuente premium con pantalla OLED para rigs enthusiast.', '/assets/products/titan-psu-1000w.jpg', 399.00, 6, 4.9, JSON_ARRAY('1200W', '80+ Platinum', 'OLED', 'Aura Sync'), 1)
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  brand_id = VALUES(brand_id),
  name = VALUES(name),
  description = VALUES(description),
  image_url = VALUES(image_url),
  price = VALUES(price),
  stock = VALUES(stock),
  rating = VALUES(rating),
  specs_json = VALUES(specs_json),
  active = VALUES(active);
